48

diff --git a/MigrationTools-36-mktemp.patch b/MigrationTools-36-mktemp.patch
--- a/MigrationTools-36-mktemp.patch
+++ b/MigrationTools-36-mktemp.patch
@@ -1,188 +1,46 @@
---- MigrationTools-36/migrate_all_netinfo_offline.sh.mktemp	Mon Feb  5 11:39:14 2001
-+++ MigrationTools-36/migrate_all_netinfo_offline.sh	Mon Feb  5 11:39:14 2001
-@@ -41,15 +41,15 @@
- INSTDIR=/usr/share/migrationtools/
+--- a/migrate_common.sh	2026-08-02 22:30:51.198578090 +0200
++++ b/migrate_common.sh	2026-08-02 22:30:51.218156724 +0200
+@@ -155,6 +155,8 @@
+ }
  
- TMPDIR="/tmp"
--ETC_PASSWD="$TMPDIR/passwd.$$.ldap"
--ETC_GROUP="$TMPDIR/group.$$.ldap"
--ETC_SERVICES="$TMPDIR/services.$$.ldap"
--ETC_PROTOCOLS="$TMPDIR/protocols.$$.ldap"
--ETC_FSTAB="$TMPDIR/fstab.$$.ldap"
--ETC_RPC="$TMPDIR/rpc.$$.ldap"
--ETC_HOSTS="$TMPDIR/hosts.$$.ldap"
--ETC_NETWORKS="$TMPDIR/networks.$$.ldap"
--ETC_ALIASES="$TMPDIR/aliases.$$.ldap"
-+ETC_PASSWD=`mktemp $TMPDIR/passwd.ldap.XXXXXX`
-+ETC_GROUP=`mktemp $TMPDIR/group.ldap.XXXXXX`
-+ETC_SERVICES=`mktemp $TMPDIR/services.ldap.XXXXXX`
-+ETC_PROTOCOLS=`mktemp $TMPDIR/protocols.ldap.XXXXXX`
-+ETC_FSTAB=`mktemp $TMPDIR/fstab.ldap.XXXXXX`
-+ETC_RPC=`mktemp $TMPDIR/rpc.ldap.XXXXXX`
-+ETC_HOSTS=`mktemp $TMPDIR/hosts.ldap.XXXXXX`
-+ETC_NETWORKS=`mktemp $TMPDIR/networks.ldap.XXXXXX`
-+ETC_ALIASES=`mktemp $TMPDIR/aliases.ldap.XXXXXX`
- EXIT=no
+ dbgen () {
++	# Secure temp file (avoid predictable /tmp names)
++	umask 077
+ 	DB="$(mktemp -t nis.ldif.XXXXXXXXXX)" || {
+ 		echo "Can't create temporary file" >&2
+ 		exit 1
+@@ -433,21 +435,23 @@
+ }
  
- question="Enter the NetInfo domain to import from [/]:"
---- MigrationTools-36/migrate_all_netinfo_online.sh.mktemp	Mon Feb  5 11:39:14 2001
-+++ MigrationTools-36/migrate_all_netinfo_online.sh	Mon Feb  5 11:39:14 2001
-@@ -41,15 +41,15 @@
- INSTDIR=/usr/share/migrationtools/
- 
- TMPDIR="/tmp"
--ETC_PASSWD="$TMPDIR/passwd.$$.ldap"
--ETC_GROUP="$TMPDIR/group.$$.ldap"
--ETC_SERVICES="$TMPDIR/services.$$.ldap"
--ETC_PROTOCOLS="$TMPDIR/protocols.$$.ldap"
--ETC_FSTAB="$TMPDIR/fstab.$$.ldap"
--ETC_RPC="$TMPDIR/rpc.$$.ldap"
--ETC_HOSTS="$TMPDIR/hosts.$$.ldap"
--ETC_NETWORKS="$TMPDIR/networks.$$.ldap"
--ETC_ALIASES="$TMPDIR/aliases.$$.ldap"
-+ETC_PASSWD=`mktemp $TMPDIR/passwd.ldap.XXXXXX`
-+ETC_GROUP=`mktemp $TMPDIR/group.ldap.XXXXXX`
-+ETC_SERVICES=`mktemp $TMPDIR/services.ldap.XXXXXX`
-+ETC_PROTOCOLS=`mktemp $TMPDIR/protocols.ldap.XXXXXX`
-+ETC_FSTAB=`mktemp $TMPDIR/fstab.ldap.XXXXXX`
-+ETC_RPC=`mktemp $TMPDIR/rpc.ldap.XXXXXX`
-+ETC_HOSTS=`mktemp $TMPDIR/hosts.ldap.XXXXXX`
-+ETC_NETWORKS=`mktemp $TMPDIR/networks.ldap.XXXXXX`
-+ETC_ALIASES=`mktemp $TMPDIR/aliases.ldap.XXXXXX`
- EXIT=no
- 
- question="Enter the NetInfo domain to import from [/]:"
---- MigrationTools-36/migrate_all_nisplus_offline.sh.mktemp	Mon Feb  5 11:39:14 2001
-+++ MigrationTools-36/migrate_all_nisplus_offline.sh	Mon Feb  5 11:43:23 2001
-@@ -41,16 +41,16 @@
- INSTDIR=/usr/share/migrationtools/
- 
- TMPDIR="/tmp"
--ETC_PASSWD="$TMPDIR/passwd.$$.ldap"
--ETC_GROUP="$TMPDIR/group.$$.ldap"
--ETC_SERVICES="$TMPDIR/services.$$.ldap"
--ETC_PROTOCOLS="$TMPDIR/protocols.$$.ldap"
--ETC_FSTAB="$TMPDIR/fstab.$$.ldap"
--ETC_RPC="$TMPDIR/rpc.$$.ldap"
--ETC_HOSTS="$TMPDIR/hosts.$$.ldap"
--ETC_NETWORKS="$TMPDIR/networks.$$.ldap"
--ETC_NETGROUP="$TMPDIR/netgroup.$$.ldap"
--ETC_ALIASES="$TMPDIR/aliases.$$.ldap"
-+ETC_PASSWD=`mktemp $TMPDIR/passwd.ldap.XXXXXX`
-+ETC_GROUP=`mktemp $TMPDIR/group.ldap.XXXXXX`
-+ETC_SERVICES=`mktemp $TMPDIR/services.ldap.XXXXXX`
-+ETC_PROTOCOLS=`mktemp $TMPDIR/protocols.ldap.XXXXXX`
-+ETC_FSTAB=`mktemp $TMPDIR/fstab.ldap.XXXXXX`
-+ETC_RPC=`mktemp $TMPDIR/rpc.ldap.XXXXXX`
-+ETC_HOSTS=`mktemp $TMPDIR/hosts.ldap.XXXXXX`
-+ETC_NETWORKS=`mktemp $TMPDIR/networks.ldap.XXXXXX`
-+ETC_NETGROUP=`mktemp $TMPDIR/netgroup.ldap.XXXXXX`
-+ETC_ALIASES=`mktemp $TMPDIR/aliases.ldap.XXXXXX`
- EXIT=no
- 
- question="Enter the NIS+ domain to import from (optional): "
---- MigrationTools-36/migrate_all_nisplus_online.sh.mktemp	Mon Feb  5 11:39:14 2001
-+++ MigrationTools-36/migrate_all_nisplus_online.sh	Mon Feb  5 11:45:18 2001
-@@ -41,16 +41,16 @@
- INSTDIR=/usr/share/migrationtools/
- 
- TMPDIR="/tmp"
--ETC_PASSWD="$TMPDIR/passwd.$$.ldap"
--ETC_GROUP="$TMPDIR/group.$$.ldap"
--ETC_SERVICES="$TMPDIR/services.$$.ldap"
--ETC_PROTOCOLS="$TMPDIR/protocols.$$.ldap"
--ETC_FSTAB="$TMPDIR/fstab.$$.ldap"
--ETC_RPC="$TMPDIR/rpc.$$.ldap"
--ETC_HOSTS="$TMPDIR/hosts.$$.ldap"
--ETC_NETWORKS="$TMPDIR/networks.$$.ldap"
--ETC_NETGROUP="$TMPDIR/netgroup.$$.ldap"
--ETC_ALIASES="$TMPDIR/aliases.$$.ldap"
-+ETC_PASSWD=`mktemp $TMPDIR/passwd.ldap.XXXXXX`
-+ETC_GROUP=`mktemp $TMPDIR/group.ldap.XXXXXX`
-+ETC_SERVICES=`mktemp $TMPDIR/services.ldap.XXXXXX`
-+ETC_PROTOCOLS=`mktemp $TMPDIR/protocols.ldap.XXXXXX`
-+ETC_FSTAB=`mktemp $TMPDIR/fstab.ldap.XXXXXX`
-+ETC_RPC=`mktemp $TMPDIR/rpc.ldap.XXXXXX`
-+ETC_HOSTS=`mktemp $TMPDIR/hosts.ldap.XXXXXX`
-+ETC_NETWORKS=`mktemp $TMPDIR/networks.ldap.XXXXXX`
-+ETC_NETGROUP=`mktemp $TMPDIR/netgroup.ldap.XXXXXX`
-+ETC_ALIASES=`mktemp $TMPDIR/aliases.ldap.XXXXXX`
- EXIT=no
- 
- question="Enter the NIS+ domain to import from (optional): "
---- MigrationTools-36/migrate_all_offline.sh.mktemp	Mon Feb  5 11:39:14 2001
-+++ MigrationTools-36/migrate_all_offline.sh	Mon Feb  5 11:39:14 2001
-@@ -42,7 +42,7 @@
- #
- 
- INSTDIR=/usr/share/migrationtools/
--DB="/tmp/nis.$$.ldif"
-+DB=`mktemp /tmp/nis.ldif.XXXXXX`
- 
- if [ "X$ETC_ALIASES" = "X" ]; then
- 	ETC_ALIASES=/etc/aliases
---- MigrationTools-36/migrate_all_online.sh.mktemp	Mon Feb  5 11:39:14 2001
-+++ MigrationTools-36/migrate_all_online.sh	Mon Feb  5 11:39:14 2001
-@@ -40,7 +40,7 @@
- 
- INSTDIR=/usr/share/migrationtools/
- 
--DB=/tmp/nis.$$.ldif
-+DB=`mktemp /tmp/nis.ldif.XXXXXX`
- 
- if [ "X$ETC_ALIASES" = "X" ]; then
- 	ETC_ALIASES=/etc/aliases
---- MigrationTools-36/migrate_all_nis_offline.sh.mktemp	Mon Feb  5 11:39:14 2001
-+++ MigrationTools-36/migrate_all_nis_offline.sh	Mon Feb  5 11:39:14 2001
-@@ -41,15 +41,15 @@
- INSTDIR=/usr/share/migrationtools/
- 
- TMPDIR="/tmp"
--ETC_PASSWD="$TMPDIR/passwd.$$.ldap"
--ETC_GROUP="$TMPDIR/group.$$.ldap"
--ETC_SERVICES="$TMPDIR/services.$$.ldap"
--ETC_PROTOCOLS="$TMPDIR/protocols.$$.ldap"
--ETC_FSTAB="$TMPDIR/fstab.$$.ldap"
--ETC_RPC="$TMPDIR/rpc.$$.ldap"
--ETC_HOSTS="$TMPDIR/hosts.$$.ldap"
--ETC_NETWORKS="$TMPDIR/networks.$$.ldap"
--ETC_ALIASES="$TMPDIR/aliases.$$.ldap"
-+ETC_PASSWD=`mktemp $TMPDIR/passwd.ldap.XXXXXX`
-+ETC_GROUP=`mktemp $TMPDIR/group.ldap.XXXXXX`
-+ETC_SERVICES=`mktemp $TMPDIR/services.ldap.XXXXXX`
-+ETC_PROTOCOLS=`mktemp $TMPDIR/protocols.ldap.XXXXXX`
-+ETC_FSTAB=`mktemp $TMPDIR/fstab.ldap.XXXXXX`
-+ETC_RPC=`mktemp $TMPDIR/rpc.ldap.XXXXXX`
-+ETC_HOSTS=`mktemp $TMPDIR/hosts.ldap.XXXXXX`
-+ETC_NETWORKS=`mktemp $TMPDIR/networks.ldap.XXXXXX`
-+ETC_ALIASES=`mktemp $TMPDIR/aliases.ldap.XXXXXX`
- EXIT=no
- 
- question="Enter the NIS domain to import from (optional): "
---- MigrationTools-36/migrate_all_nis_online.sh.mktemp	Mon Feb  5 11:39:14 2001
-+++ MigrationTools-36/migrate_all_nis_online.sh	Mon Feb  5 11:39:14 2001
-@@ -41,15 +41,15 @@
- INSTDIR=/usr/share/migrationtools/
- 
- TMPDIR="/tmp"
--ETC_PASSWD="$TMPDIR/passwd.$$.ldap"
--ETC_GROUP="$TMPDIR/group.$$.ldap"
--ETC_SERVICES="$TMPDIR/services.$$.ldap"
--ETC_PROTOCOLS="$TMPDIR/protocols.$$.ldap"
--ETC_FSTAB="$TMPDIR/fstab.$$.ldap"
--ETC_RPC="$TMPDIR/rpc.$$.ldap"
--ETC_HOSTS="$TMPDIR/hosts.$$.ldap"
--ETC_NETWORKS="$TMPDIR/networks.$$.ldap"
--ETC_ALIASES="$TMPDIR/aliases.$$.ldap"
-+ETC_PASSWD=`mktemp $TMPDIR/passwd.ldap.XXXXXX`
-+ETC_GROUP=`mktemp $TMPDIR/group.ldap.XXXXXX`
-+ETC_SERVICES=`mktemp $TMPDIR/services.ldap.XXXXXX`
-+ETC_PROTOCOLS=`mktemp $TMPDIR/protocols.ldap.XXXXXX`
-+ETC_FSTAB=`mktemp $TMPDIR/fstab.ldap.XXXXXX`
-+ETC_RPC=`mktemp $TMPDIR/rpc.ldap.XXXXXX`
-+ETC_HOSTS=`mktemp $TMPDIR/hosts.ldap.XXXXXX`
-+ETC_NETWORKS=`mktemp $TMPDIR/networks.ldap.XXXXXX`
-+ETC_ALIASES=`mktemp $TMPDIR/aliases.ldap.XXXXXX`
- EXIT=no
- 
- question="Enter the NIS domain to import from (optional): "
+ tmpfd_gen () {
+-	TEMP_DIR="$(mktemp -dt)" || {
++	# Secure temp dir + files (mktemp; avoid predictable names)
++	umask 077
++	TEMP_DIR="$(mktemp -dt migrationtools.XXXXXXXXXX)" || {
+ 		echo "Can't create temporary directory" >&2
+ 		exit 1
+ 	}
+-	ETC_PASSWD="$TEMP_DIR/passwd.ldap"
+-	ETC_GROUP="$TEMP_DIR/group.ldap"
++	ETC_PASSWD="$(mktemp "$TEMP_DIR/passwd.ldap.XXXXXX")"
++	ETC_GROUP="$(mktemp "$TEMP_DIR/group.ldap.XXXXXX")"
+ 	if [ "$MIGRATION_TYPE" != 'min' ]; then
+-		ETC_SERVICES="$TEMP_DIR/services.ldap"
+-		ETC_PROTOCOLS="$TEMP_DIR/protocols.ldap"
+-		[ ! -z "$(echo "$@" | grep 'fstab')" ] && ETC_FSTAB="$TEMP_DIR/fstab.ldap"
+-		ETC_RPC="$TEMP_DIR/rpc.ldap"
+-		ETC_HOSTS="$TEMP_DIR/hosts.ldap"
+-		ETC_NETWORKS="$TEMP_DIR/networks.ldap"
+-		[ ! -z "$(echo "$@" | grep 'netgroup')" ] && ETC_NETGROUP="$TEMP_DIR/netgroup.ldap"
+-		ETC_ALIASES="$TEMP_DIR/aliases.ldap"
++		ETC_SERVICES="$(mktemp "$TEMP_DIR/services.ldap.XXXXXX")"
++		ETC_PROTOCOLS="$(mktemp "$TEMP_DIR/protocols.ldap.XXXXXX")"
++		[ ! -z "$(echo "$@" | grep 'fstab')" ] && ETC_FSTAB="$(mktemp "$TEMP_DIR/fstab.ldap.XXXXXX")"
++		ETC_RPC="$(mktemp "$TEMP_DIR/rpc.ldap.XXXXXX")"
++		ETC_HOSTS="$(mktemp "$TEMP_DIR/hosts.ldap.XXXXXX")"
++		ETC_NETWORKS="$(mktemp "$TEMP_DIR/networks.ldap.XXXXXX")"
++		[ ! -z "$(echo "$@" | grep 'netgroup')" ] && ETC_NETGROUP="$(mktemp "$TEMP_DIR/netgroup.ldap.XXXXXX")"
++		ETC_ALIASES="$(mktemp "$TEMP_DIR/aliases.ldap.XXXXXX")"
+ 	fi
+ 	EXIT=no
+ }
